### ISSUE TITLE
Mounting `my_elasticsearch.yml` to extend the default config is currently broken

### ISSUE THREAD

**Issue by tormi** [wunderio/drupal-project#255]
Tested `elasticsearch:7.16.2` with Lando `3.6.1` & current config. Mounting `my_elasticsearch.yml` to extend* the default config is currently broken due to permission issus.

```
services:
  elasticsearch:
    type: "elasticsearch:7.16.2"
    # Replace `true` with `9200` for proxy http://localhost:9200.
    portforward: 9200
    overrides:
      environment:
        ELASTICSEARCH_HEAP_SIZE: 1024m
        # Comma, semi-colon or space separated list of plugins to install at initialization.
        ELASTICSEARCH_PLUGINS: analysis-icu
      volumes:
        # Extend the default configuration with custom settings like
        # allowing CORS requests at `.lando/my_elasticsearch.yml`.
        # @see: https://github.com/bitnami/bitnami-docker-elasticsearch#configuration-file.
        - "./.lando/my_elasticsearch.yml:/opt/bitnami/elasticsearch/config/my_elasticsearch.yml"
```

*- https://github.com/bitnami/bitnami-docker-elasticsearch#configuration-file
