### ISSUE TITLE
Start using official Elasticsearch & Kibana images for arm64 support

### ISSUE THREAD

**Issue by tormi** [wunderio/drupal-project#277]
Current Lando/Bitnami ES setup doesn't support `arm64` architecture, let's switch over to official images. Silta is also using them.

References:
- https://www.elastic.co/guide/en/elasticsearch/reference/7.17/docker.html
- https://hub.docker.com/layers/elastic/elasticsearch/7.17.0/images/sha256-4f588d1001c207d6217e61747df8752c5d2a04c41e3a235c621bfa3a57e352f5?context=explore
- https://hub.docker.com/layers/elastic/kibana/7.17.0/images/sha256-7963042ab4dfe95a5577c6c1bcb871a1c63cb1e92f61403945f298ba0a7dcbfe?context=explore

**Comment by tormi** [comment]
Alternative approach would be to use pure Docker Compose setup:

## `.lando.yml`

```
compose:
  - ./.lando/docker-compose.yml

proxy:
  elasticsearch:
    - elasticsearch.lndo.site:9200
  kibana:
    - kibana.lndo.site:5601
```

## `.lando/docker-compose.yml`

```
# https://www.elastic.co/guide/en/elastic-stack-get-started/7.17/get-started-docker.html
version: "3.8"
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.0
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - esdata:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: docker.elastic.co/kibana/kibana:7.17.0
    ports:
      - 5601:5601

volumes:
  esdata:
    driver: local
```

**Comment by tormi** [comment]
Managing plugins requires `elasticsearch-plugins.yml`: https://www.elastic.co/guide/en/elasticsearch/plugins/7.17/manage-plugins-using-configuration-file.html

```
plugins:
  - id: analysis-icu
  - id: repository-azure
  - id: custom-mapper
    location: https://example.com/archive/custom-mapper-1.0.0.zip
```
