### ISSUE TITLE
Configure monolog as default

### ISSUE THREAD

**Issue by Juhani-moilanen** [wunderio/drupal-project#304]
Add monolog config so that all new projects use it by default 

- add "monolog.services.yml" to sites/default/
- use "monolog.services.yml" in settings.php

"monolog.services.yml"

```
parameters:
  monolog.channel_handlers:
    default: ['stream']
  monolog.processors: ['message_placeholder', 'current_user', 'request_uri', 'ip', 'referer']

services:
  monolog.handler.stream:
    class: Monolog\Handler\StreamHandler
    arguments: ['php://stderr', 10, 'monolog.level.debug']
```
This will spit out Drupal logs so that sumologic can get them

in settings.php 
`$settings['container_yamls'][] = 'sites/default/monolog.services.yml';`

I think it would be nice if every env used monolog by default and for lando maybe add something similar to 
 [Vantaa projects](https://github.com/wunderio/client-fi-vantaa-web/blob/master/.lando/tooling/devel-enable.sh) `lando devel-enable` that would enable modules that help with  local development and debugging
