### ISSUE TITLE
Add elasticsearch Silta resources example

### ISSUE THREAD

**Issue by misterjoonas** [wunderio/drupal-project#322]
Would be good to have some sane elasticsearch resources example. Something like
```
# Elasticsearch used for site search.
elasticsearch:
  esJavaOpts: -Xmx350m -Xms350m
  resources:
    requests:
      cpu: 50m
      memory: 600M
    limits:
      cpu: 1000m
      memory: 1536M
```
