### ISSUE TITLE
Replace file storage with Google's Filestore volume

### ISSUE THREAD

**Issue by tormi** [wunderio/drupal-project#323]
Let's replace default file storage with Google's Filestore volume, https://github.com/wunderio/silta/blob/master/docs/gcp_filestore_migration.md#changing-storage-for-a-new-deployment-project

```
mounts:
  public-files:
    enabled: true
    storage: 10G
    mountPath: /app/web/sites/default/files
    storageClassName: nfs-shared
  private-files:
    enabled: true
    storage: 1G
    mountPath: /app/private
    storageClassName: nfs-shared
```
