### ISSUE TITLE
Lando: Add phpunit tool.

### ISSUE THREAD

**Issue by tormi** [wunderio/drupal-project#44]
## Proposal

Add `phpunit` to Lando tooling section:

```
tooling:
  phpunit:
    service: appserver
    cmd: /app/vendor/bin/phpunit
```

`lando phpunit -c web/core --testsuite unit --exclude-group Composer,DependencyInjection,PageCache,Setup` gives now also `@expectedDeprecation` messages, test result for `"drupal/core": "8.7.x-dev"`:

<img width="946" alt="Screenshot 2019-04-02 at 02 01 48" src="https://user-images.githubusercontent.com/146800/55364988-6af50100-54eb-11e9-9dbb-152cb23a1b79.png">
