### ISSUE TITLE
Add Codeception tool

### ISSUE THREAD

**Issue by tormi** [wunderio/drupal-project#73]
Currently, there is a `lando codeception` tool defined at `.lando.yml`, but it has never been working because there's no _codeception_ package added to `composer.json`:

```
tooling:
  codeception:
    service: appserver
    description: Run codeception
    cmd:
      - ./vendor/bin/codecept
      - "--env=lando"
```

Let's add either `codeception/codeception` or `guncha25/drupal-codeception`.

See also: 
- https://github.com/wunderio/drupal-project/issues/37
- https://github.com/wunderio/drupal-project/pull/20/commits/6240c751d3c565925fb3c3f914ce0dab49476b3e

cc: @guncha25 , @floretan

**Comment by tormi** [comment]
I've removed non-functional `lando codecept` tool for now here: https://github.com/wunderio/drupal-project/pull/71/commits/9bf67d505ce79aa359bce7a9210b6ddd7e17447d

**Comment by tormi** [comment]
Readme: 

- `lando codecept <commands>` - run [Codeception](https://codeception.com/) tests.

Tool definition:

```
  codecept:
    description: Runs codeception commands
    cmd:
      - appserver: ./vendor/bin/codecept
```
